### ISSUE TITLE
No module named microbit

### ISSUE THREAD

**Issue by rachilli2** [musabkilic/MicroBike#3]
when i run controller.py it returns this error

**Comment by musabkilic** [comment]
Please see [this](https://github.com/whaleygeek/bitio#getting-started) to set up the bitio(microbit) module. Let me know if you have problems setting it up.

**Comment by rachilli2** [comment]
ive definitely installed it because it displays the logo and ive tested the counter example too

**Comment by musabkilic** [comment]
Try moving `controller.py` to the same folder as the examples(bitio/src/), hopefully this should resolve the issue.

**Comment by musabkilic** [comment]
I'm closing the issue, let me know if you have problems.

Kind regards,
Musab

**Comment by rachilli2** [comment]
It is now saying when i run the code NameError: name 'accelerometer' is not defined
